/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Constant.Constant;
import Control.MainControl;
import static GUI.Main.pathFile;
import Ultil.DragAndDrop;
import Ultil.OpenFileDialog;

/**
 *
 * @author quang
 */
public class Main_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Main_GUI
     */
    private static final String[] FILTER_EXTS = { "*.xls", "*.csv" };
    public Main_GUI() {
        initComponents();
        int chon_option = 0;
        if (buttonGroup1.getSelection().equals(rbExactly.getModel())) {
            chon_option = Constant.EXACTLY;
        } else if (buttonGroup1.getSelection().equals(rbExpand.getModel())) {
            chon_option = Constant.EXPAND;
        } else {
            chon_option = Constant.NOTEXPAND;
        }
        DragAndDrop dad = new DragAndDrop();
        dad.doActionDragAndDrop(tbPathFile, lblDrapAndDrop, lblResult, txtResultListKeyWords, chon_option);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tbPathFile = new javax.swing.JTextField();
        btnClickMe = new javax.swing.JButton();
        lblDrapAndDrop = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultListKeyWords = new javax.swing.JTextArea();
        lblResult = new javax.swing.JLabel();
        btnCost = new javax.swing.JButton();
        rbExactly = new javax.swing.JRadioButton();
        rbExpand = new javax.swing.JRadioButton();
        rbNotExactly = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMARTLINKS.VN");

        btnClickMe.setText("...");
        btnClickMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickMeActionPerformed(evt);
            }
        });

        lblDrapAndDrop.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblDrapAndDrop.setForeground(new java.awt.Color(255, 51, 51));
        lblDrapAndDrop.setText("Drag And Drop File Here");
        lblDrapAndDrop.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));

        txtResultListKeyWords.setColumns(20);
        txtResultListKeyWords.setRows(5);
        jScrollPane1.setViewportView(txtResultListKeyWords);

        lblResult.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lblResult.setForeground(new java.awt.Color(255, 51, 51));
        lblResult.setText("Result");
        lblResult.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));

        btnCost.setText("Do It!!!");
        btnCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCostActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbExactly);
        rbExactly.setSelected(true);
        rbExactly.setText("Exactly");

        buttonGroup1.add(rbExpand);
        rbExpand.setText("Expand");

        buttonGroup1.add(rbNotExactly);
        rbNotExactly.setText("No Primary Keyword");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbPathFile, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(btnClickMe, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDrapAndDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(rbExactly)
                        .addGap(46, 46, 46)
                        .addComponent(rbExpand)
                        .addGap(26, 26, 26)
                        .addComponent(rbNotExactly)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCost, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbPathFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClickMe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDrapAndDrop, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rbNotExactly)
                    .addComponent(btnCost, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbExpand)
                    .addComponent(rbExactly))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCostActionPerformed
        MainControl mc = new MainControl();
        int chon_option = 0;
        if (buttonGroup1.getSelection().equals(rbExactly.getModel())) {
            chon_option = Constant.EXACTLY;
        } else if (buttonGroup1.getSelection().equals(rbExpand.getModel())) {
            chon_option = Constant.EXPAND;
        } else {
            chon_option = Constant.NOTEXPAND;
        }
        mc.Xu_Ly_Button_Cost(tbPathFile.getText(), lblResult, txtResultListKeyWords, chon_option);
    }//GEN-LAST:event_btnCostActionPerformed

    private void btnClickMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickMeActionPerformed
//        OpenFileDialog openFile = new OpenFileDialog();
//				String pathfile = openFile.openFileDialog(FILTER_EXTS,);
//				tbPathFile.setText(pathfile);
//				pathFile = pathfile;
    }//GEN-LAST:event_btnClickMeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClickMe;
    private javax.swing.JButton btnCost;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDrapAndDrop;
    private javax.swing.JLabel lblResult;
    private javax.swing.JRadioButton rbExactly;
    private javax.swing.JRadioButton rbExpand;
    private javax.swing.JRadioButton rbNotExactly;
    private javax.swing.JTextField tbPathFile;
    private javax.swing.JTextArea txtResultListKeyWords;
    // End of variables declaration//GEN-END:variables
}
